### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by data4pass** [jamieboyd/RFIDTagReader#2]
Could you kindly clarify the licence of this repository? I would like to use its code for a project of mine.

> ["You may not be aware of this, but legally, without a license, no one can use your code."](https://github.com/organicinternet/magento-configurable-simple/issues/222#issuecomment-135201411)

Related link: https://opensource.stackexchange.com/questions/1720/

Thank you.

**Comment by jamieboyd** [comment]
Sorry. My bad. MIT License added. Most permissive of coming options. Good luck with the code, ask me if you have any questions.
